# Generated by Django 5.1 on 2024-09-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bull',
            fields=[
                ('bull_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('breed', models.CharField(choices=[('HOL', 'Holstein'), ('JER', 'Jersey'), ('ANG', 'Angus'), ('OTH', 'Other'), ('HER', 'Hereford'), ('SIM', 'Simmental'), ('LIM', 'Limousin'), ('CHA', 'Charolais')], default='HOL')),
                ('health_status', models.CharField(choices=[('P', 'Poor'), ('G', 'Good'), ('E', 'Excellent')], default='G')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('cow_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('breed', models.CharField(choices=[('HOL', 'Holstein'), ('JER', 'Jersey'), ('ANG', 'Angus'), ('OTH', 'Other'), ('HER', 'Hereford'), ('SIM', 'Simmental'), ('LIM', 'Limousin'), ('CHA', 'Charolais')], default='HOL')),
                ('health_status', models.CharField(choices=[('P', 'Poor'), ('G', 'Good'), ('E', 'Excellent')], default='G')),
                ('pregnancy_status', models.CharField(choices=[('NP', 'Not Pregnant'), ('PR', 'Pregnant'), ('IH', 'In Heat'), ('DR', 'Dry'), ('LC', 'Lactating'), ('FR', 'Fresh'), ('CV', 'Calving')], default='NP')),
                ('number_of_calvings', models.IntegerField()),
                ('last_calving_date', models.DateField()),
                ('milk_production', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('account_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('breeding_id', models.AutoField(primary_key=True, serialize=False)),
                ('breeding_date', models.DateField()),
                ('breeding_method', models.CharField(choices=[('NS', 'Natural Service'), ('AI', 'Artificial Insemination')], default='NS')),
                ('resulting_pregnancy', models.BooleanField()),
                ('comments', models.TextField()),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herdhub.bull')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herdhub.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Calf',
            fields=[
                ('calf_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M')),
                ('dob', models.DateField()),
                ('calving_method', models.CharField(choices=[('NU', 'Natural Unassisted'), ('AS', 'Assisted'), ('CS', 'C-Section'), ('IN', 'Induction'), ('EA', 'Emergency Assistance')], default='NU')),
                ('comments', models.TextField()),
                ('breeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herdhub.breeding')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_on', models.DateField()),
                ('message', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herdhub.user')),
            ],
        ),
        migrations.AddField(
            model_name='cow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herdhub.user'),
        ),
        migrations.AddField(
            model_name='bull',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herdhub.user'),
        ),
    ]
