# Generated by Django 5.1 on 2024-09-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herdhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cow',
            table='Cow',
        ),
    ]
