# Generated by Django 5.1 on 2024-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herdhub', '0003_calf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_on',
            field=models.CharField(),
        ),
    ]
