# Generated by Django 5.1 on 2024-09-10 13:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herdhub', '0005_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='bull',
            name='image_id',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, verbose_name='image'),
        ),
    ]
