# Generated by Django 5.1 on 2024-09-11 09:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herdhub', '0006_bull_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calf',
            name='image_id',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='cow',
            name='image_id',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, verbose_name='image'),
        ),
    ]
