# Generated by Django 5.1 on 2024-09-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herdhub', '0007_calf_image_id_cow_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeding',
            name='breeding_method',
            field=models.CharField(choices=[('Natural Service', 'Natural Service'), ('Artificial Insemination', 'Artificial Insemination')], default='Natural Service'),
        ),
        migrations.AlterField(
            model_name='breeding',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bull',
            name='breed',
            field=models.CharField(choices=[('Holstein', 'Holstein'), ('Jersey', 'Jersey'), ('Angus', 'Angus'), ('Other', 'Other'), ('Hereford', 'Hereford'), ('Simmental', 'Simmental'), ('Limousin', 'Limousin'), ('Charolais', 'Charolais')], default='Holstein'),
        ),
        migrations.AlterField(
            model_name='bull',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bull',
            name='health_status',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Good'),
        ),
        migrations.AlterField(
            model_name='calf',
            name='breeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herdhub.breeding'),
        ),
        migrations.AlterField(
            model_name='calf',
            name='calving_method',
            field=models.CharField(choices=[('Natural Unassisted', 'Natural Unassisted'), ('Assisted', 'Assisted'), ('C-Section', 'C-Section'), ('Induction', 'Induction'), ('Emergency Assistance', 'Emergency Assistance')], default='Natural Unassisted'),
        ),
        migrations.AlterField(
            model_name='calf',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calf',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(choices=[('Holstein', 'Holstein'), ('Jersey', 'Jersey'), ('Angus', 'Angus'), ('Other', 'Other'), ('Hereford', 'Hereford'), ('Simmental', 'Simmental'), ('Limousin', 'Limousin'), ('Charolais', 'Charolais')], default='Holstein'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='health_status',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Good'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='milk_production',
            field=models.IntegerField(default='2000'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='number_of_calvings',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='pregnancy_status',
            field=models.CharField(choices=[('Not Pregnant', 'Not Pregnant'), ('Pregnant', 'Pregnant'), ('In Heat', 'In Heat'), ('Dry', 'Dry'), ('Lactating', 'Lactating'), ('Fresh', 'Fresh'), ('Calving', 'Calving')], default='Not Pregnant'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=3000),
        ),
    ]
