# Generated by Django 5.1 on 2024-09-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herdhub', '0008_alter_breeding_breeding_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calf',
            name='breeding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herdhub.breeding'),
        ),
    ]
