# Generated by Django 5.1 on 2024-09-18 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herdhub', '0009_alter_calf_breeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='milk_production',
            field=models.IntegerField(default='2000', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='number_of_calvings',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
