# Generated by Django 5.1 on 2024-09-23 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herdhub', '0011_alter_bull_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bull',
            name='registration_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Registration number must be alphanumeric only, 10 characters max.', regex='^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='calf',
            name='registration_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Registration number must be alphanumeric only, 10 characters max.', regex='^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='registration_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Registration number must be alphanumeric only, 10 characters max.', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
